type SolvedEntry = {
  question: {
    difficulty: 'Easy' | 'Medium' | 'Hard';
    questionId: string;
    questionFrontendId?: string;
    title?: string;
  };
  topicTags?: { name: string }[];
  timestamp: number;
};

export class RootReadmeService {
  generate(problems: Record<string, SolvedEntry>): string {
    const entries = Object.entries(problems).map(([slug, data]) => ({ slug, ...data }));

    const easy = entries.filter((e) => e.question.difficulty === 'Easy').length;
    const medium = entries.filter((e) => e.question.difficulty === 'Medium').length;
    const hard = entries.filter((e) => e.question.difficulty === 'Hard').length;
    const total = entries.length;

    if (total === 0) {
      return [
        '# 🔥 LitCode Solutions',
        '',
        '*No problems synced yet. Start solving on LeetCode!*',
        '',
        '---',
        '<sub>Synced by [LitCode](https://github.com/Satharva2004/LitCode)</sub>',
      ].join('\n');
    }

    const topicMap: Record<string, typeof entries> = {};
    entries.forEach((e) => {
      const tags = e.topicTags?.length ? e.topicTags : [{ name: 'Uncategorized' }];
      tags.forEach((tag) => {
        if (!topicMap[tag.name]) topicMap[tag.name] = [];
        if (!topicMap[tag.name].find((x) => x.slug === e.slug)) {
          topicMap[tag.name].push(e);
        }
      });
    });

    const sortedTopics = Object.entries(topicMap).sort((a, b) => b[1].length - a[1].length);

    const diffEmoji = (d: string) => (d === 'Easy' ? '🟢' : d === 'Medium' ? '🟡' : '🔴');
    const fmtDate = (ts: number) => new Date(ts).toISOString().slice(0, 10);
    const bar = (n: number, max: number, len = 12) => {
      const f = Math.round((n / Math.max(max, 1)) * len);
      return '█'.repeat(f) + '░'.repeat(len - f);
    };

    const topicSections = sortedTopics
      .map(([topic, probs]) => {
        const sorted = [...probs].sort((a, b) => {
          const aId = parseInt(a.question.questionFrontendId || a.question.questionId || '0');
          const bId = parseInt(b.question.questionFrontendId || b.question.questionId || '0');
          return aId - bId;
        });

        const rows = sorted
          .map((p) => {
            const id = p.question.questionFrontendId || p.question.questionId;
            const title = p.question.title || p.slug;
            return `| ${id} | [${title}](./${id}-${p.slug}) | ${diffEmoji(p.question.difficulty)} ${p.question.difficulty} | ${fmtDate(p.timestamp)} |`;
          })
          .join('\n');

        return [
          '<details>',
          `<summary><b>${topic}</b> &nbsp;·&nbsp; ${probs.length} problem${probs.length !== 1 ? 's' : ''}</summary>`,
          '',
          '| # | Problem | Difficulty | Solved |',
          '|---|---------|------------|--------|',
          rows,
          '',
          '</details>',
        ].join('\n');
      })
      .join('\n\n');

    return [
      '<div align="center">',
      '',
      '# 🔥 LitCode Solutions',
      '',
      `[![Total](https://img.shields.io/badge/Total-${total}-blue?style=flat-square)](.)`,
      `[![Easy](https://img.shields.io/badge/Easy-${easy}-2ea44f?style=flat-square)](.)`,
      `[![Medium](https://img.shields.io/badge/Medium-${medium}-d97706?style=flat-square)](.)`,
      `[![Hard](https://img.shields.io/badge/Hard-${hard}-dc2626?style=flat-square)](.)`,
      '',
      `*Auto-synced by [LitCode](https://github.com/Satharva2004/LitCode) · Last updated ${fmtDate(Date.now())}*`,
      '',
      '</div>',
      '',
      '---',
      '',
      '## 📊 Progress',
      '',
      '| Difficulty | Count | Progress |',
      '|:----------|------:|---------|',
      `| 🟢 Easy | ${easy} | \`${bar(easy, total)}\` |`,
      `| 🟡 Medium | ${medium} | \`${bar(medium, total)}\` |`,
      `| 🔴 Hard | ${hard} | \`${bar(hard, total)}\` |`,
      `| **Total** | **${total}** | |`,
      '',
      '---',
      '',
      '## 🗂️ Problems by Topic',
      '',
      topicSections,
      '',
      '---',
      '',
      '<sub>Generated by <a href="https://github.com/Satharva2004/LitCode">LitCode</a></sub>',
    ].join('\n');
  }
}
